"""Session 049 Skeptic-ablated dialectical cycle.

Parallel to :mod:`guarded_cycle` but with the Skeptic ANTITHESIS step
removed. The pipeline becomes:

    Architect (THESIS) -> OracleFirewall -> (synthetic null Skeptic) -> OracleJudge

The firewall still runs — only the Skeptic reasoning step is ablated.
A synthetic null Skeptic message (confidence 0.0, no assertions, empty
narrative) is substituted so :meth:`OracleJudge.compute_verdict` can be
invoked without modifying its signature. The OracleJudge remains
deterministic and untouched.

Rationale: the design question for Session 049 is "does the Skeptic
layer rescue framing the firewall cannot see?" Removing the Skeptic
LLM call (and feeding OracleJudge a 0.0-confidence rebuttal instead of
a real one) produces a counterfactual answer to that.

Public API:
    run_ablated_cycle       -- Skeptic-ablated single-turn cycle
    AblatedCycleResult      -- Frozen result with firewall + variant metadata
    build_null_skeptic_message -- Helper for tests and composition
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import datetime
from typing import Callable, Optional, TYPE_CHECKING

from ares.dialectic.agents.architect import ArchitectAgent
from ares.dialectic.agents.context import TurnContext
from ares.dialectic.agents.oracle import OracleJudge, OracleNarrator
from ares.dialectic.coordinator.firewall import FirewallVerdict, OracleFirewall
from ares.dialectic.coordinator.orchestrator import CycleError, CycleResult
from ares.dialectic.evidence.packet import EvidencePacket
from ares.dialectic.messages.assertions import Assertion
from ares.dialectic.messages.protocol import (
    DialecticalMessage,
    MessageBuilder,
    MessageType,
    Phase,
    Priority,
)

if TYPE_CHECKING:
    from ares.dialectic.agents.strategies.protocol import (
        NarrativeGenerator,
        ThreatAnalyzer,
    )


# Session 049 convention: every cycle-variant result carries a label so
# downstream tooling can be cross-checked against FramingBenchmarkResultV2.
PIPELINE_VARIANT_LABEL: str = "ablated"


@dataclass(frozen=True)
class AblatedCycleResult:
    """Result of a Skeptic-ablated analysis cycle.

    Attributes:
        cycle_result: The underlying CycleResult. ``skeptic_message`` is the
            synthetic null Skeptic (0.0 confidence, no assertions).
        firewall_verdict: Firewall validation of the Architect's output.
        used_sanitized: Whether sanitized firewall output replaced the
            Architect's tainted interpretation before the verdict.
        pipeline_variant: Always ``"ablated"`` — present for parity with
            FramingBenchmarkResultV2 and other downstream consumers.
    """

    cycle_result: CycleResult
    firewall_verdict: FirewallVerdict
    used_sanitized: bool
    pipeline_variant: str = PIPELINE_VARIANT_LABEL


# =============================================================================
# Synthetic null Skeptic
# =============================================================================


def build_null_skeptic_message(
    *,
    cycle_id: str,
    packet_id: str,
    turn_number: int = 2,
) -> DialecticalMessage:
    """Build a valid-but-empty Skeptic REBUTTAL message.

    The null Skeptic has:
        * confidence = 0.0
        * no assertions
        * no narrative
        * turn_number = ``turn_number`` (defaults to 2, the ANTITHESIS slot)

    Passing this message to :meth:`OracleJudge.compute_verdict` means the
    decision table sees a zero-confidence rebuttal: the verdict depends
    almost entirely on the Architect's confidence. That is the intended
    ablation — the Skeptic's reasoning is removed, and the synthetic
    message is just the envelope the OracleJudge requires.

    Args:
        cycle_id: Cycle identifier shared with the Architect message.
        packet_id: Evidence packet identifier.
        turn_number: Turn number for the synthetic message; defaults to 2.

    Returns:
        A DialecticalMessage of type REBUTTAL with confidence 0.0.
    """
    builder = MessageBuilder(
        source_agent="ares-skep-ablated",
        packet_id=packet_id,
        cycle_id=cycle_id,
    )
    builder.set_target("broadcast")
    builder.set_phase(Phase.ANTITHESIS)
    builder.set_turn(turn_number)
    builder.set_type(MessageType.REBUTTAL)
    builder.set_priority(Priority.NORMAL)
    builder.set_confidence(0.0)
    builder.set_narrative(
        "Skeptic ablated — no benign rebuttal generated by design."
    )
    return builder.build()


# =============================================================================
# Sanitization (shared logic with guarded_cycle — intentionally duplicated
# so ablated_cycle has no runtime dependency on guarded_cycle's internals)
# =============================================================================


def _build_sanitized_message(
    original: DialecticalMessage,
    sanitized_interpretations: tuple[str, ...],
) -> DialecticalMessage:
    """Rebuild an Architect message with sanitized assertion interpretations."""
    sanitized_assertions = [
        Assertion(
            assertion_id=assertion.assertion_id,
            assertion_type=assertion.assertion_type,
            fact_ids=assertion.fact_ids,
            interpretation=sanitized_interpretations[i],
            operator=assertion.operator,
            threshold=assertion.threshold,
        )
        for i, assertion in enumerate(original.assertions)
    ]
    return DialecticalMessage(
        message_id=original.message_id,
        timestamp=original.timestamp,
        source_agent=original.source_agent,
        target_agent=original.target_agent,
        schema_version=original.schema_version,
        reply_to=original.reply_to,
        packet_id=original.packet_id,
        cycle_id=original.cycle_id,
        phase=original.phase,
        turn_number=original.turn_number,
        message_type=original.message_type,
        assertions=sanitized_assertions,
        unknowns=list(original.unknowns),
        confidence=original.confidence,
        narrative=original.narrative,
        priority=original.priority,
        persist=original.persist,
        tags=list(original.tags),
    )


def _make_clean_firewall_verdict() -> FirewallVerdict:
    """Pass-through verdict used when no firewall is supplied."""
    return FirewallVerdict(
        passed=True,
        violations=(),
        taint_score=0.0,
        sanitized_output=None,
        timestamp=datetime.utcnow(),
    )


# =============================================================================
# Public API
# =============================================================================


def run_ablated_cycle(
    packet: EvidencePacket,
    *,
    threat_analyzer: Optional["ThreatAnalyzer"] = None,
    narrative_generator: Optional["NarrativeGenerator"] = None,
    firewall: Optional[OracleFirewall] = None,
    agent_id_prefix: str = "ares",
    include_narration: bool = True,
    null_skeptic_factory: Callable[..., DialecticalMessage] = (
        build_null_skeptic_message
    ),
) -> AblatedCycleResult:
    """Run a Skeptic-ablated single-turn dialectical cycle.

    The flow is intentionally asymmetric with :func:`run_guarded_cycle`:

    1. Architect runs THESIS.
    2. Firewall validates the Architect's output. If the firewall flags
       the message, the sanitized output replaces the Architect's
       interpretation text in-place; no hot-swap is attempted — this is
       the Session 049 ablation, not a resilient production pipeline.
    3. A synthetic null Skeptic message (0.0 confidence, no assertions)
       is built and handed to OracleJudge along with the Architect
       message.
    4. OracleJudge computes the verdict deterministically.
    5. OracleNarrator optionally explains the verdict for the record.

    Args:
        packet: Frozen EvidencePacket.
        threat_analyzer: Strategy for the Architect.
        narrative_generator: Strategy for the OracleNarrator.
        firewall: OracleFirewall instance. ``None`` disables validation
            (a pass-through verdict is recorded).
        agent_id_prefix: Prefix for generated agent IDs.
        include_narration: If True, run OracleNarrator.
        null_skeptic_factory: Builder for the synthetic null Skeptic
            message; exposed for tests only.

    Returns:
        AblatedCycleResult with the same surface shape the comparison
        report consumes for Session 048 runs.

    Raises:
        ValueError: If packet is not frozen.
        CycleError: If any phase fails.
    """
    if not packet.is_frozen:
        raise ValueError("Packet must be frozen before running a cycle")

    started_at = datetime.utcnow()
    cycle_uuid = uuid.uuid4().hex[:8]
    cycle_id = f"cycle-ablated-{cycle_uuid}"
    prefix = agent_id_prefix

    # --- Architect ---
    architect = ArchitectAgent(
        agent_id=f"{prefix}-arch-{cycle_uuid}",
        threat_analyzer=threat_analyzer,
    )
    try:
        architect.observe(packet)
        thesis_context = TurnContext(
            cycle_id=cycle_id,
            packet_id=packet.packet_id,
            snapshot_id=packet.snapshot_id,
            phase=Phase.THESIS,
            turn_number=1,
            max_turns=3,
            seen_fact_ids=frozenset(),
        )
        architect_result = architect.act(thesis_context)
    except Exception as exc:
        raise CycleError(
            f"THESIS phase failed: {exc}",
            phase=Phase.THESIS,
            cycle_id=cycle_id,
            cause=exc,
        ) from exc

    if architect_result.message is None:
        raise CycleError(
            "Architect produced no message",
            phase=Phase.THESIS,
            cycle_id=cycle_id,
        )
    architect_message = architect_result.message

    # --- Firewall ---
    if firewall is not None:
        firewall_verdict = firewall.validate(architect_message, packet)
    else:
        firewall_verdict = _make_clean_firewall_verdict()

    used_sanitized = False
    if not firewall_verdict.passed:
        # Require sanitized fallback or fail closed: never propagate the
        # original tainted message to the (null) Skeptic and OracleJudge.
        sanitized = firewall_verdict.sanitized_output
        if sanitized is None:
            raise CycleError(
                "Firewall failed-closed: output rejected "
                "and no sanitized fallback available",
                phase=Phase.THESIS,
                cycle_id=cycle_id,
            )
        architect_message = _build_sanitized_message(
            architect_message, sanitized,
        )
        used_sanitized = True

    # --- Null Skeptic (synthetic) ---
    null_skeptic = null_skeptic_factory(
        cycle_id=cycle_id,
        packet_id=packet.packet_id,
    )

    # --- Verdict ---
    try:
        verdict = OracleJudge.compute_verdict(
            architect_message, null_skeptic, packet,
        )
    except Exception as exc:
        raise CycleError(
            f"Verdict computation failed: {exc}",
            phase=Phase.SYNTHESIS,
            cycle_id=cycle_id,
            cause=exc,
        ) from exc

    # --- Optional narration ---
    narrator_message: Optional[DialecticalMessage] = None
    if include_narration:
        narrator = OracleNarrator(
            agent_id=f"{prefix}-oracle-{cycle_uuid}",
            verdict=verdict,
            narrative_generator=narrative_generator,
        )
        try:
            narrator.observe(packet)
            synthesis_context = TurnContext(
                cycle_id=cycle_id,
                packet_id=packet.packet_id,
                snapshot_id=packet.snapshot_id,
                phase=Phase.SYNTHESIS,
                turn_number=3,
                max_turns=3,
                seen_fact_ids=frozenset(verdict.supporting_fact_ids),
            )
            narrator_result = narrator.act(synthesis_context)
        except Exception as exc:
            raise CycleError(
                f"SYNTHESIS phase failed: {exc}",
                phase=Phase.SYNTHESIS,
                cycle_id=cycle_id,
                cause=exc,
            ) from exc
        if narrator_result.message is None:
            raise CycleError(
                "OracleNarrator produced no message",
                phase=Phase.SYNTHESIS,
                cycle_id=cycle_id,
            )
        narrator_message = narrator_result.message

    completed_at = datetime.utcnow()
    duration_ms = int((completed_at - started_at).total_seconds() * 1000)

    cycle_result = CycleResult(
        cycle_id=cycle_id,
        packet_id=packet.packet_id,
        verdict=verdict,
        architect_message=architect_message,
        skeptic_message=null_skeptic,
        narrator_message=narrator_message,
        started_at=started_at,
        completed_at=completed_at,
        duration_ms=duration_ms,
    )

    return AblatedCycleResult(
        cycle_result=cycle_result,
        firewall_verdict=firewall_verdict,
        used_sanitized=used_sanitized,
    )
